<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoreBase\CoreBase.csproj" />
    <ProjectReference Include="..\CoreModbus\CoreModbus.csproj" />
    <ProjectReference Include="..\CoreOpcUA\CoreOpcUA.csproj" />
    <ProjectReference Include="..\CoreSCADA\CoreSCADA.csproj" />
  </ItemGroup>

</Project>
